export {
  AgentChatTransport,
  type AgentChatTransportOptions,
  type AgentStreamMeta,
} from './agent-chat-transport.js';
export {
  AgentClient,
  type AgentClientOptions,
  AgentHttpError,
  type CancelResult,
  type QuotaToday,
  type ThreadPatch,
} from './client.js';
// Named, never `export *`: a wildcard re-export from a barrel defeats a bundler's ability to see
// which names a consumer actually uses, and has broken a downstream build in this ecosystem before.
export {
  type AnyToolUIPart,
  ChatInput,
  type ChatInputProps,
  type ChatStatus,
  formatRelativeTime,
  MessageItem,
  type MessageItemClassNames,
  type MessageItemProps,
  MessageItemView,
  type MessageItemViewProps,
  MessageList,
  type MessageListClassNames,
  type MessageListProps,
  type MessageUsageInfo,
  type RenderReasoningFn,
  type RenderTextFn,
  type RenderToolGroupFn,
  type RenderToolPartFn,
  DEFAULT_SPEECH_LANG,
  loadStoredSpeechLang,
  persistSpeechLang,
  type SpeechLanguage,
  SPEECH_LANGUAGES,
  type SpeechRecognitionHook,
  useSpeechRecognition,
  type UseSpeechRecognitionOptions,
} from './components/index.js';
export { storedMessageToUiMessage } from './stored-message-to-ui-message.js';
export {
  type AggregatedTurnUsage,
  type StoredTurnMetadata,
  storedThreadToUiMessages,
} from './stored-thread-to-ui-messages.js';
export {
  type ApprovalBlockOptions,
  type BuildBlocksOptions,
  buildTranscriptBlocks,
  type ChatTranscript,
  describeTimestamp,
  describeUsage,
  type ElicitationBlockOptions,
  extractMessageText,
  type RetrievedPassage,
  type StickToBottom,
  type StickToBottomOptions,
  type TimestampInfo,
  type TranscriptActionState,
  type TranscriptBlock,
  type TranscriptCopyState,
  type TranscriptEditState,
  type TranscriptElicitationBlock,
  type TranscriptElicitationOutcome,
  type TranscriptItem,
  type TranscriptItemOptions,
  type TranscriptQuestion,
  type TranscriptQuestionOption,
  type TranscriptReasoningBlock,
  type TranscriptSettleState,
  type TranscriptSource,
  type TranscriptSourcesBlock,
  type TranscriptStopState,
  type TranscriptTextBlock,
  type TranscriptToolBlock,
  type TranscriptToolCall,
  type TranscriptWindow,
  type UsageSummary,
  useChatTranscript,
  type UseChatTranscriptOptions,
  useStickToBottom,
  useTranscriptItem,
  type UseTranscriptItemOptions,
} from './transcript/index.js';
export { useAgentChat, type UseAgentChatOptions } from './use-agent-chat.js';
